export const PRINTING_ORDER_LIST_REQUEST = "PRINTING_ORDER_LIST_REQUEST";
export const PRINTING_ORDER_LIST_SUCCESS = "PRINTING_ORDER_LIST_SUCCESS";
export const PRINTING_ORDER_LIST_FAIL = "PRINTING_ORDER_LIST_FAIL";

export const PRINTING_ORDER_DETAILS_REQUEST = "PRINTING_ORDER_DETAILS_REQUEST";
export const PRINTING_ORDER_DETAILS_SUCCESS = "PRINTING_ORDER_DETAILS_SUCCESS";
export const PRINTING_ORDER_DETAILS_FAIL = "PRINTING_ORDER_DETAILS_FAIL";

export const PRINTING_ORDER_DELIVERED_REQUEST = "PRINTING_ORDER_DELIVERED_REQUEST";
export const PRINTING_ORDER_DELIVERED_SUCCESS = "PRINTING_ORDER_DELIVERED_SUCCESS";
export const PRINTING_ORDER_DELIVERED_FAIL = "PRINTING_ORDER_DELIVERED_FAIL";
export const PRINTING_ORDER_DELIVERED_RESET = "PRINTING_ORDER_DELIVERED_RESET";
