export const SLIDESHOW_LIST_REQUEST = "SLIDESHOW_LIST_REQUEST";
export const SLIDESHOW_LIST_SUCCESS = "SLIDESHOW_LIST_SUCCESS";
export const SLIDESHOW_LIST_FAIL = "SLIDESHOW_LIST_FAIL";

export const SLIDESHOW_DELETE_REQUEST = "SLIDESHOW_DELETE_REQUEST";
export const SLIDESHOW_DELETE_SUCCESS = "SLIDESHOW_DELETE_SUCCESS";
export const SLIDESHOW_DELETE_FAIL = "SLIDESHOW_DELETE_FAIL";

export const SLIDESHOW_CREATE_REQUEST = "SLIDESHOW_CREATE_REQUEST";
export const SLIDESHOW_CREATE_SUCCESS = "SLIDESHOW_CREATE_SUCCESS";
export const SLIDESHOW_CREATE_FAIL = "SLIDESHOW_CREATE_FAIL";
export const SLIDESHOW_CREATE_RESET = "SLIDESHOW_CREATE_RESET";